config/routes.rb
Basicvoting::Application.routes.draw do
  resources :organizations

  resources :booths

  resources :people

end

app/models/booth.rb
class Booth < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :organization_persons
  has_many :people, :through => :organization_persons
end

app/models/organization_person.rb
class OrganizationPerson < ActiveRecord::Base
  belongs_to :organization
  belongs_to :person
  
  # NOTE: the :update_only option issue, check this link 
  # http://masonoise.wordpress.com/2010/07/23/rails-and-forms-using-accepts_nested_attributes_for/ 
  accepts_nested_attributes_for :organization, :update_only => true
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :organization_persons
  has_many :organizations, :through => :organization_persons
  
  accepts_nested_attributes_for :organization_persons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  # GET /booths
  # GET /booths.json
  def index
    @booths = Booth.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @booths }
    end
  end

  # GET /booths/1
  # GET /booths/1.json
  def show
    @booth = Booth.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booth }
    end
  end

  # GET /booths/new
  # GET /booths/new.json
  def new
    @booth = Booth.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booth }
    end
  end

  # GET /booths/1/edit
  def edit
    @booth = Booth.find(params[:id])
  end

  # POST /booths
  # POST /booths.json
  def create
    @booth = Booth.new(params[:booth])

    respond_to do |format|
      if @booth.save
        format.html { redirect_to @booth, notice: 'Booth was successfully created.' }
        format.json { render json: @booth, status: :created, location: @booth }
      else
        format.html { render action: "new" }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /booths/1
  # PUT /booths/1.json
  def update
    @booth = Booth.find(params[:id])

    respond_to do |format|
      if @booth.update_attributes(params[:booth])
        format.html { redirect_to @booth, notice: 'Booth was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booths/1
  # DELETE /booths/1.json
  def destroy
    @booth = Booth.find(params[:id])
    @booth.destroy

    respond_to do |format|
      format.html { redirect_to booths_url }
      format.json { head :ok }
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    # @person.organization_persons.build.build_organization   # this will create a new organization
    3.times { @person.organization_persons.build }
    # @organizations = Organization.find :all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booths_helper.rb
module BoothsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/booths/_form.html.erb
<%= form_for(@booth) do |f| %>
  <% if @booth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booth.errors.count, "error") %> prohibited this booth from being saved:</h2>

      <ul>
      <% @booth.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :district %><br />
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :booth_station_no %><br />
    <%= f.text_field :booth_station_no %>
  </div>
  <div class="field">
    <%= f.label :booth_no %><br />
    <%= f.text_field :booth_no %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booths/edit.html.erb
<h1>Editing booth</h1>

<%= render 'form' %>

<%= link_to 'Show', @booth %> |
<%= link_to 'Back', booths_path %>

app/views/booths/index.html.erb
<h1>Listing booths</h1>

<table>
  <tr>
    <th>District</th>
    <th>Booth station no</th>
    <th>Booth no</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booths.each do |booth| %>
  <tr>
    <td><%= booth.district %></td>
    <td><%= booth.booth_station_no %></td>
    <td><%= booth.booth_no %></td>
    <td><%= booth.description %></td>
    <td><%= link_to 'Show', booth %></td>
    <td><%= link_to 'Edit', edit_booth_path(booth) %></td>
    <td><%= link_to 'Destroy', booth, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booth', new_booth_path %>

app/views/booths/new.html.erb
<h1>New booth</h1>

<%= render 'form' %>

<%= link_to 'Back', booths_path %>

app/views/booths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>District:</b>
  <%= @booth.district %>
</p>

<p>
  <b>Booth station no:</b>
  <%= @booth.booth_station_no %>
</p>

<p>
  <b>Booth no:</b>
  <%= @booth.booth_no %>
</p>

<p>
  <b>Description:</b>
  <%= @booth.description %>
</p>


<%= link_to 'Edit', edit_booth_path(@booth) %> |
<%= link_to 'Back', booths_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basicvoting</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_male %><br />
    <%= f.check_box :is_male %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :family_origin %><br />
    <%= f.text_field :family_origin %>
  </div>
  
  <div>
  	<%= f.fields_for :organization_persons do | role_form | %>	
		<%=role_form.label "Work as (role)" %>  :  <%= role_form.text_field :role %>
		<%=role_form.label "Work in (organization)" %>  :  <%= role_form.select :organization_id, Organization.all.collect{|p| [p.name, p.id ]}, { :include_blank => true }  %>	<br/><br/>
	<% end %>
  </div>
  
  <div>TODO: allow admin to be able to add an organization from this link? Or must go through other links?</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Is male</th>
    <th>Birthday</th>
    <th>Bio</th>
    <th>Family origin</th>
	<th>Roles</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.is_male %></td>
    <td><%= person.birthday %></td>
    <td><%= person.bio %></td>
    <td><%= person.family_origin %></td>
	
	<td>
		<% if person.organization_persons.size > 0 %>
		<dl>
			<% person.organization_persons.each do | rel | %>
				<li> <%= rel.role %>  in:  
					<% if rel.organization.respond_to?(:name) %><%= rel.organization.name %>  <% end %> 
				</li>
			<% end %>
		</dl>
		<% else %>
			No role assigned.
		<% end %>
	</td>
	
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Is male:</b>
  <%= @person.is_male %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday %>
</p>

<p>
  <b>Bio:</b>
  <%= @person.bio %>
</p>

<p>
  <b>Family origin:</b>
  <%= @person.family_origin %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>